SRCMPI	= writeconfigfile.c
OBJMPI	=$(SRCMPI:.c=.o)
CC	= cc
PP	= -g 

#CFLAGS  = -O3 -I /home/nx01/nx01/adrianj/papi/include -I /home/nx01/nx01/adrianj/mxml/include $(PP)
#LIBS    = -L/home/nx01/nx01/adrianj/mxml/lib -lmxml -lpthread
#CFLAGS  = -O3 -I papi/include -I mxml/ $(PP)
#LIBS    = -L/lustre/home/z04/adrianj/NodeResourceUsageImpact/mxml -lmxml -lpthread
CFLAGS  = -O3 -I papi/include -I mxml/ $(PP)
LIBS    = -L/home/z19/z19/adrianj/NodeResourceUsageImpact/mxml -lmxml -lpthread

PRGMPI	= writeconfigfile

main:	$(PRGMPI) 

.c.o:	Makefile
	$(CC) -c $(CFLAGS) $(ELIBS) $<

$(PRGMPI):$(OBJMPI) inject_definitions.h
	$(CC) $(LDFLAGS) -o $@ $(OBJMPI) $(LIBS)

clean:
	rm -fr $(TMP) $(OBJMPI) $(PRGMPI) core
