SRCWRITE= writeconfigfile.c
OBJWRITE=$(SRCWRITE:.c=.o)
SRCREAD= readconfigfile.c
OBJREAD=$(SRCREAD:.c=.o)
CC	= cc
PP	= -g 

#CFLAGS  = -O3 -I /home/nx01/nx01/adrianj/papi/include -I /home/nx01/nx01/adrianj/mxml/include $(PP)
#LIBS    = -L/home/nx01/nx01/adrianj/mxml/lib -lmxml -lpthread
#CFLAGS  = -O3 -I papi/include -I mxml/ $(PP)
#LIBS    = -L/lustre/home/z04/adrianj/NodeResourceUsageImpact/mxml -lmxml -lpthread
CFLAGS  = -O3 -I papi/include -I mxml/ $(PP)
LIBS    = -L/home/z19/z19/adrianj/NodeResourceUsageImpact/mxml -lmxml -lpthread

PRGWRITE= writeconfigfile
PRGREAD= readconfigfile

main:	$(PRGWRITE) $(PRGREAD) 

.c.o:	Makefile
	$(CC) -c $(CFLAGS) $(ELIBS) $<

$(PRGWRITE):$(OBJWRITE) inject_definitions.h
	$(CC) $(LDFLAGS) -o $@ $(OBJWRITE) $(LIBS)

$(PRGREAD):$(OBJREAD) inject_definitions.h
	$(CC) $(LDFLAGS) -o $@ $(OBJREAD) $(LIBS)

clean:
	rm -fr $(TMP) $(OBJWRITE) $(OBJREAD) $(PRGWRITE) $(PRGREAD) core
