SRCMPI	= writeconfigfile.c
OBJMPI	=$(SRCMPI:.c=.o)
CC	= icc
PP	= -g 

CFLAGS  = -O3 -I papi/include -I mxml/ $(PP)
LIBS    = -L/home/z01/z01/adrianj/NodeResourceUsageImpact/mxml -lmxml -lpthread

PRGMPI	= writeconfigfile

main:	$(PRGMPI) 

.c.o:	Makefile
	$(CC) -c $(CFLAGS) $(ELIBS) $<

$(PRGMPI):$(OBJMPI) inject_definitions.h
	$(CC) $(LDFLAGS) -o $@ $(OBJMPI) $(LIBS)

clean:
	rm -fr $(TMP) $(OBJMPI) $(PRGMPI) core
