SRCMPI	= mpi_intercept_library.c inject_config.c hello.c

OBJMPI	=$(SRCMPI:.c=.o)

CC	= cc
PP	= -g #-DDEBUG 

CFLAGS  = -O3 -I mxml/ -I papi/include $(PP)
LIBS    = -L/home/z01/z01/adrianj/NodeResourceUsageImpact/mxml -lmxml -lpthread

PRGMPI	= hello

main:	$(PRGMPI) 

.c.o:	Makefile
	$(CC) -c $(CFLAGS) $(ELIBS) $<

$(PRGMPI):$(OBJMPI) Makefile.mpi definitions.h
	$(CC) $(LDFLAGS) -o $@ $(OBJMPI) $(LIBS)

clean:
	rm -fr $(TMP) $(OBJMPI) $(PRGMPI) core
