#!/bin/bash --login
#
#PBS -l select=3
#PBS -N testinj
#PBS -A z19-cse
#PBS -l walltime=0:10:0

cd /work/z01/z01/adrianj

cp ~/NodeResourceUsageImpact/hello .
cp ~/NodeResourceUsageImpact/inject .inject

ulimit -c unlimited

# Run the parallel program
date
#aprun -n 16 -N 8 ./hello 1 & 
#aprun -n 16 -N 8 ./hello 2 
#wait
aprun -n 72 -N 24 -j 1 ./hello 1 
cp -f inject_log_* ~/NodeResourceUsageImpact/ 2>/dev/null 
rm -f inject_log_*
date

